kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployments

spec:
  replicas: 2
  selector:
    matchLabels:
      mynode: master

  template:
    metadata:
      labels:
        mynode: master
    spec:
      containers:
      - name: c00
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo hello-students; sleep 10; done"]

