apiVersion: v1
kind: Pod
metadata:
  name: mypod

spec:
  initContainers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "echo 'Hello-Sai' > /tmp/c1dir/saifile; sleep 20"]

    volumeMounts:
    - name: myvol
      mountPath: "/tmp/c1dir"

  containers:
  - name: c2
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo `cat /tmp/c2dir/saifile`; sleep 10; done"]

    volumeMounts:
    - name: myvol
      mountPath: "/tmp/c2dir"

  volumes:
  - name: myvol
    emptyDir: {}


