kind: Pod
apiVersion: v1
metadata:
  name: testpod

spec:
  containers:
  - name: c00
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do Hello-Sai; sleep 15; done"]

  - name: c01
    image: httpd
    ports:
      - containerPort: 80
