apiVersion: v1
kind: Pod
metadata:
  name: constraints-mem-demo

spec:
  containers:
  - name: c00
    image: nginx

    resources:
      limits:
        memory: 800Mi
      requests:
        memory: 600Mi
