kind: Pod
apiVersion: v1
metadata:
  name: testpod3

spec:
  containers:
  - name: c01
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo Hello-Varsha; done"]

  - name: c02
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-Sujii; done"]

