kind: ReplicationController
apiVersion: v1
metadata:
  name: myreplicationcontroller

spec:
  replicas: 2
  selector:
    myname: sai

  template:
    metadata:
      labels:
        myname: sai
    spec:
      containers:
      - name: c00
        image: centos
        command: ["/bin/bash", "-c", "while true; do echo hello-sai; sleep 10; done"]
